### ISSUE TITLE
What version to use?

### ISSUE THREAD

**Issue by simendsjo** [logary/logary#107]
logary.github.io is for v2.0, while the nuget packages are for v4.0.6. The examples on the website doesn't work. The Logary.Targets.Riemann package doesn't include a lib folder. Seems the API has changed in the master branch too, so I had to check the examples in the repo from the 4.0.6 tag.

Are there any plans to update the documentation and examples? Or is it recommended to use v2 rather than v4?

**Comment by haf** [comment]
v3 is what's documented on the site, sorry about the confusion there. v3 is very stable and used extensively in production, but has more dependencies than v4.

v4 is increasingly stable (but in alpha right now). Unfortunately it's only documented through extensive unit tests.

v4.sln in `src` shows what targets we support at the time of writing for v4. Riemann is not supported, because simply I don't use it right now. All targets that are not in `v4.sln` have empty nuget packages right now.

Porting a target from v3 to v4 takes be about 20 minutes and if you want to use it I can do it for you if I can debit an hour's worth of time. That would include some Skype time to get you started (about 40 minutes-to an hour)

**Comment by simendsjo** [comment]
Thanks for the prompt answer! I got both 4.0.6 and 3.6.1 working. I'm only experimenting with, and evaluating, Logary at the moment, and we don't have any production code using it. Would you recommend using 3.6.1, 4.0.6 or master as learning material?

**Comment by haf** [comment]
4.0.6 is master currently.

If you're primarily C#, use 3.x

If you're primarily F#, use 4.x

4.x has a slightly higher GC churn/requirement. At normal logging rates (20-100 messages per second for a process) this is not an issue. At about 800 messages per second you need 1-2 GiB. At 1600 messages per second you need 4 GiB. Then it levels out (this was tested on 128 GiB machines, so GC might be more aggressive on lower-specced systems), with server GC/concurrent GC. Persistent, non GC-able size is 2 KiB, basically just two references; one for the registry and one for the active logger.

4.x runs the units test 30x as fast, and is generally more performant.

4.x is smarter when it comes to shipping values, in that there's a new data model in place, using static method overloading to translate logging values to the DOM (Data object model). 3.x uses reflection more.

4.x has much better metrics-support, has a really nice batching buffer with a limit, so it drops messages that targets cannot consume in time (like it should, otherwise you'll balloon your mem). 3.x has unbounded buffers.

Decide for yourself.
