### ISSUE TITLE
Influx Target stops logging if influx connection is lost

### ISSUE THREAD

**Issue by mavnn** [logary/logary#148]
Discovered when restarting the influx db being written to, no further investigation so far.

**Comment by haf** [comment]
This is probably because of this line:

https://github.com/logary/logary/blob/master/src/Logary/Supervisor.fs#L29-L32

Which states to only retry ten times. The connection may be down much longer than five seconds.

Similarly, we need more Supervisor tests https://github.com/logary/logary/blob/master/src/tests/Logary.Tests/Supervisor.fs

**Comment by haf** [comment]
Fixed in Target_InfluxDb.fs
