### ISSUE TITLE
Facade to Logary literate target prints expanded TimeSpan

### ISSUE THREAD

**Issue by haf** [logary/logary#202]
<img width="958" alt="screen shot 2016-11-06 at 21 24 49" src="https://cloud.githubusercontent.com/assets/193115/20041324/923c00d8-a467-11e6-9642-9f515782983d.png">

/cc @adamchester 

I think it's mostly a matter of transferring gauges to actual gauges as values rather than fields (that contain arbitrary objects).

**Comment by adamchester** [comment]
How does this happen?

**Comment by adamchester** [comment]
I see; in the facade we store the original values (eg. `TimeSpan`), then we adapted to Logary it gets converted via `Value.ofObject` right?

**Comment by adamchester** [comment]
This random thought I had a while back may be related, depending on how we address this: https://github.com/logary/logary/blob/master/src/Logary/TemplateFormat.fs#L14

**Comment by haf** [comment]
Yes, that's correct.

**Comment by adamchester** [comment]
Just thinking out loud at this stage....

In message templates (and Serilog) we have a list of common/system types (also configurable) that are considered [`scalar`](https://github.com/messagetemplates/messagetemplates-fsharp/blob/master/src/FsMessageTemplates/MessageTemplates.fs#L384); scalars shouldn't be treated as objects which can have their structure captured (eg. Even you put `@` in the template, it wouldn't try to capture the fields). It's also generally a requirement that scalars are immutable.

This works, in part, because the data model keeps a boxed copy of the original value at the capturing stage.

However, the facade doesn't really have a data model now; everything remains as obj. Additionally, Logary proper data model doesn't have any way to store these types, other than string (which potentially looses a fair amount of fidelity early in the pipeline).

**Comment by adamchester** [comment]
Looks like [this](https://github.com/logary/logary/blob/dcc261ca9ef26a3c5f15f6be7995eea4119df920/src/Logary/DataModel.fs#L211-L238) is the equivalent list of 'scalars' in Logary:

```fsharp
let rec ofObject : obj -> Value = function
  | null -> String ""
  // Built-in types
  | :? bool as b     -> Bool b
  | :? int8 as i     -> Int64 (int64 i)
  | :? uint8 as i    -> Int64 (int64 i)
  | :? int16 as i    -> Int64 (int64 i)
  | :? uint16 as i   -> Int64 (int64 i)
  | :? int32 as i    -> Int64 (int64 i)
  | :? uint32 as i   -> Int64 (int64 i)
  | :? int64 as i    -> Int64 (int64 i)
  | :? uint64 as i   -> Float (float i)
  | :? bigint as i   -> BigInt i
  | :? decimal as d  -> Float (float d)
  | :? float32 as f32-> Float (float f32)
  | :? float as f    -> Float f
  | :? char as c     -> String (string c)
  | :? string as s   -> String s

  // Common BCL types
  | :? Guid as g             -> String (string g)
  | :? DateTime as dt        -> String (dt.ToUniversalTime().ToString("o"))
  | :? DateTimeOffset as dto -> String (dto.ToString("o"))
  | :? exn as e              -> Object (exceptionToStringValueMap ofObject e)
```

Notable that `TimeSpan` is missing.

**Comment by haf** [comment]
The general idea is that gauges are their own values with units, so just performing this change doesn't fix the issue; but makes it easier to read the output at least. The real fix should be in the facade.
