### ISSUE TITLE
NodaTime 2.0 Incompatibility

### ISSUE THREAD

**Issue by HoraceGonzalez** [logary/logary#239]
Getting an exception while creating a new logger: 

```
Unhandled Exception: System.Exception: System.MissingFieldException: Field not found: 'NodaTime.SystemClock.Instance'.
   at Logary.Configuration.Config.ConfigureLogary(String serviceName)
   at Logary.Configuration.Config.WithLogaryManager(String serviceName, FSharpFunc`2 fConf)
```

Pinning NodaTime to 1.3.2 resolved the issue.

**Comment by haf** [comment]
Cool, NodaTime was released yesterday!

This issue is not an issue though. The nuget clearly states >= 1.x and we're using semver. When I finish the new engine, I'll push the updated NodaTime with it.

**Comment by HoraceGonzalez** [comment]
Thanks, @haf!

**Comment by piaste** [comment]
> This issue is not an issue though. The nuget clearly states >= 1.x and we're using semver. When I finish the new engine, I'll push the updated NodaTime with it.

I pulled Logary 4.2 from NuGet and it pulled NodaTime 2.0 with it, which crashed immediately.

The `.nuspec` in the package doesn't specify version number:

    <dependency id="NodaTime" version="1.3.2" />

To enforce semver, it should read `[1.3.2,2.0)`.

I'm not familiar with the albacore build tool you're using, so I'm not sure if it's possible to make it generate the correct dependency version.

If it's not, this should be prominently displayed in the readme, because it's pretty bad that `paket install logary`  / `install-package logary` results in a runtime exception at hello world.

**Comment by haf** [comment]
Yes, it's this line: https://github.com/Albacore/albacore/blob/master/lib/albacore/nuget_model.rb#L144 – the `d.version` is a string, so a fix could be to replace that expression with ```ruby
upper = XSemVer.parse(d.version)
upper.major += 1
# ...

x.dependency id: d.id, version: "[#{d.version}, #{upper.to_s})"
```
