### ISSUE TITLE
Best practices with Logary on SOA / enterprise / multi-node environments, and endpoint configurations?

### ISSUE THREAD

**Issue by Thorium** [logary/logary#245]
I'm quite happy with the current Readme.md, but there are little practical questions that it doesn't hint:

1. Is the best practice to create multiple loggers in general? If I have multiple categories of messages, how should I group them, should I create many loggers? `getLoggerByName` kind of hints to that direction. But will there be lot of noise with this solution? Do you in general have a hundred lines of configuration script? Let's say e.g. that I want to log separately server-side exceptions as errors, but I also want to see user's javascript-errors from our website. Errors, but not so critical that I would like to flood my log with those. Is the best practice to create multiple loggers?

```fsharp
let serverLogger =
	withLogaryManager "ServerSideItems" (
		withTargets [
			//...
		] >> withRules [
			//...
		]
	) |> run

let clientLogger = // Like this?
	withLogaryManager "ClientSideItems" (
		withTargets [
			//...
		] >> withRules [
			//...
		]
	) |> run
```

2. If I have multiple duplicate machines, how should I identify those? Is the best practice to use dynamic endpoint names? E.g. a web-server farm where one webserver is not working correctly. My log is having messages, how do I identify where they came from? 

```fsharp
let serverLogger =
	withLogaryManager (myserverIP + "ServerSideItems") ( // Like this?
```

3. Timing on non-single-operation: There is `Logary.Logger.time`, which supports asyncs and everything, but what if I have more object oriented style of timing, let's say I have a base-class having methods `BeforeOperation` and `AfterOperation`? Should I measure the time manually in the base-class and manual create a Gauge to send to the server, or is there a better way? Endpoint names seems to be hierarchical, so should I say that the last part of endpoint name is user-session+method-call-name? Will there be a drawback to create 100 000 endpoints?

**Comment by Thorium** [comment]
4. How should I do negative/anti-events: e.g. a real-time user counter, should I create a Gauge +1 when user enters and a Gauge 0 or Gauge -1 when user leaves?

**Comment by haf** [comment]
1. Multiple **loggers**, yes; multiple **logary**s, no. You use **rule**s to vary/filter messages. 
<img width="474" alt="screen shot 2017-04-19 at 21 56 06" src="https://cloud.githubusercontent.com/assets/193115/25199417/1d21a7ac-254b-11e7-85ed-293a2cdb42ed.png">

What's an error changes with context; if you use Suave Reporter, then you'll get what your JS thinks are errors as errors into Logary. I try to keep the error levels the 'same' throughout all services, frontend and backend. Equivalence here is what action is needed by a human or a system; which is what meaning I attach to the level, mostly.

Suave Reporter takes the names from the JS namespaces, btw, and we send all those to our logging infrastructure.

2. Multiple machines should be created with `withMiddleware` when you create the config, to set a `contextField` with the machine name. Although, I don't log machine names myself, because they're completely replaceable and have no meaning. If a machine fails, a new is brought up. Your example is the semantic **service name**, i.e. "LendingSiteWeb" or "PaymentGateway".

3. You mean PointName, not endpoint, I suppose? In general Logary takes extremely low amounts of memory. We have a few buffers (500 sizeof<int32> per target) but besides that it's mostly a collection of object references (maybe 20-40 of them when I profiled last), so 540 bytes of memory for the core and another few kilobytes for reflection caches? Plus GC generated which of course can be substantial depending on how much data you're sending. 2000 points every second plateaus at 3 GiB of garbage on a 256 GiB-ram machine at about 10% CPU of two cores (out of 36).

So back to topic; you can create anything you like as long as you log a message with the information in the end. I don't have much experience with OOP APIs, but there's a bit of work with a disposable implementation that supports timer hierarchies and a timer duration partitioning in the user code, on the new engine branch; which will be added to the C# API as we go.

4. Right now, you have to use the APIs given https://github.com/logary/logary/blob/master/examples/Logary.ConsoleApp/Program.fs#L98 – but I aim for the engine to support indexing and thus pub/sub between metric nodes. It's still WIP though. I send a gauge for each event to influx, because that's not my current bottleneck, yes; otherwise you can use the withMetric support to accumulate values and not send as much data.

**Comment by Thorium** [comment]
Thanks!

**Comment by Thorium** [comment]
Other answers made sense, but 1. is not clear yet... I'm not using Suave nor Suave Reporter. 
About the image: `yield rule "console" "Suave" Info` would maybe make sense if I would know what is the `rule` function... The basic problem is: How to filter the messages to flow to just another target: 

```fsharp
let serverLogger =
   withLogaryManager "AllItems" (
      withTargets [
         Console.create (Console.empty) "A"
         Console.create (Console.empty) "B"
      ] >> withRules [
         yield rule "A" "MyMessagesType1" Info
         yield rule "B" "MyMessagesType2" Info
      ]) |> run

Message.eventWarn ("I want this info go to just B but not A") 
|> Logger.logSimple (Logary.Logging.getCurrentLogger())
```

**Comment by haf** [comment]
First of all, the static method call `getCurrentLogger` should be called statically.

---

Suppose you have one logger `Corp.Ns.App.A.ClassName` and another `Corp.Ns.App.B.ClassName`, you'd create a rule `hiera = Regex @"App[.]A"; target = "A"` and another one `hiera = Regex @"App[.]B"; target = "B"` to get the desired behaviour.

Note that Message.name defaults to that of the logger, but you can override it in individual messages.

**Comment by Thorium** [comment]
Ok, without regex:s, this seems to work:

```fsharp
let logger = 
    withLogaryManager "testAppInsights" (
        withTargets [
            Logary.Targets.File.create fileConf1 "A" // a.txt
            Logary.Targets.File.create fileConf2 "B" // b.txt
        ] >> withRules [
            Rule.createForTarget "A" 
            |> Rule.setMessageFilter(fun m -> m.name <> PointName.ofSingle "special")
            Rule.createForTarget "B" 
            |> Rule.setMessageFilter(fun m -> m.name = PointName.ofSingle "special")
        ] >> withMiddleware (fun next msg ->
                  msg |> Message.setContextValue "host" (String (System.Net.Dns.GetHostName()))
            )
    ) |> run

let cur = Logary.Logging.getCurrentLogger()
Message.eventWarn ("I want this info go to just B but not A") 
|> Message.setName (PointName.ofSingle "special")
|> Logger.logSimple cur
```
