### ISSUE TITLE
Incorrect version restriction for Nodatime dependency in nuspec

### ISSUE THREAD

**Issue by samhanes** [logary/logary#280]
The nuspec lists the NodaTime dependency as 
`<dependency id="NodaTime" version="1.3.2" />`

That means that users who add `nuget Logary` to their `paket.dependencies` end up pulling NodaTime > 2.0, which causes an immediate error at runtime.  It looks the dependency should read:
`<dependency id="NodaTime" version="1.3.2, 2.0.0)" />` as detailed in https://github.com/logary/logary/issues/239

That issue suggests that is a problem in albacore; I confess my ruby is took weak to attempt a PR on that side.

I noticed a similar issue with `Castle.Core` in `Logary.Adapters.Facade`; I will log an issue there as well.

**Comment by haf** [comment]
You could just bump the version of albacore to solve it, but we have v5 in progress; so the PR should go to the releases/v4 branch then.

**Comment by samhanes** [comment]
Got it, I'll give that a try.  Thanks!

**Comment by haf** [comment]
Also, release v4 branch needs to be branched off just before the commit that merges the windows-per counters branch.

**Comment by Thorium** [comment]
If the NodaTime update is too much work, I suggest just to add the restriction. It's quite annoying to use Logary in a larger project now: 

   1. run paket update
   2. the software compiles but observe it fails at runtime because of Nodatime
   3. change the Nodatime manually back to 1.3.2 from paket.lock
   4. run paket install again
   5. observe that install fails because Github thinks using paket so often is a DoS attack.
   6. wait or change connection from wlan to mobile phone endpoint

**Comment by haf** [comment]
It's really not much work. Someone has to do it.

**Comment by haf** [comment]
Or even don't PR it and I'll take your work from your fork with the changes, because you can't PR branch creations.

**Comment by haf** [comment]
Closing due to lack of response.
