### ISSUE TITLE
Logary v5 requireLicenseAcceptance

### ISSUE THREAD

**Issue by sergey-tihon** [logary/logary#344]
The current `nuspec` of `Logary` `5.0.0-beta.15` says that package does not require license acceptance. Seems that it is not longer true for v5 beta packages.

Could you please change it to 
```xml
<!-- 
     If true, this value prompts the user to accept the license when 
     installing the package. 
-->
<requireLicenseAcceptance>true</requireLicenseAcceptance>
```
this should help end-users to be aware of license change and to be sure that they follow license terms.

Thanks.

<img width="941" alt="win10_-_1803__april_" src="https://user-images.githubusercontent.com/1197905/41195763-62caa8a6-6c3c-11e8-908d-1f5a9cf3633e.png">

**Comment by haf** [comment]
It's still unneeded because;

 1. You're always required to accept the license of software you're using, so there's no legal ambiguity even with this flag off.
 2. The beta already does its license check itself, so if you're not following the license it'll tell you. Hence, there's no risk for you involved.
