### ISSUE TITLE
Logary.Targets.OpenTracing

### ISSUE THREAD

**Issue by ctaggart** [logary/logary#393]
I see that there is a new Logary.Targets.Jaeger for 5.0.0-rc.1.
https://www.nuget.org/packages/Logary.Targets.Jaeger/5.0.0-rc.1

Jaeger and others build on top of OpenTracing. For example, you can see the dependency here:
https://www.nuget.org/packages/Jaeger/

What about building a target that targeted OpenTracing directly?
https://www.nuget.org/packages/OpenTracing/

**Comment by haf** [comment]
It's a good question. What's your motivation for wanting one?

**Comment by ctaggart** [comment]
My understanding is that OpenTracing provides an API with others can use. For my case, I wish to send the traces to Wavefront instead of Jaeger.

https://opentracing.io/registry/?s=C%23
![image](https://user-images.githubusercontent.com/80104/53054733-57c62e80-3473-11e9-8374-86a3739fd283.png)

**Comment by lust4life** [comment]
@ctaggart  i think there is some misunderstanding here, since `OpenTracing` is a specification, so there is no official infrastructure implementation there, even https://github.com/opentracing/opentracing-csharp/tree/master/src/OpenTracing is just a bunch of API (interfaces), so if you want to send traces to Jaeger you need through it's implementation (sdk/thrif protocol), same with Wavefront, we need add a target for wavefront through [`wavefront-sdk-csharp` ](https://github.com/wavefrontHQ/wavefront-sdk-csharp#create-a-wavefrontproxyclient) just like [`wavefront-opentracing-sdk-csharp`](https://github.com/wavefrontHQ/wavefront-opentracing-sdk-csharp) did ,  implement `OpenTracing` api. Then you can just can change it's(`OpenTracing's`) implementation to send data to different targets if you only use `OpenTracing` api at the top level. 

`logary` here is some bit like the `OpenTracing` api, you use logary's api at top level, and your data will be sent to differnet target by configuration.

**Comment by ctaggart** [comment]
Thank you @lust4life. It seams to me that Google and Microsoft are both putting effort into OpenCensus instead and that may be a better route to go. It was a spec and an official implementation in the works kind of like gRPC. Their [OpenCusus Agent](https://opencensus.io/agent/) looks like it may help solve getting data to different backends for me.

**Comment by lust4life** [comment]
that is interesting, thanks for the insight, will check it later,seems promising.

**Comment by haf** [comment]
@ctaggart We have a bit of that brewing in Logary actually; since we support Spans now and they are mapped into messages we can do something more native to .net:

 - Your .Net project spawns Logary with a Shipper target, with a PUSH socket to tcp://rutta:10010 (https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/patterns/pushpull.html)
 - You deploy Rutta with a PULL socket listener (Router mode) and a Zipkin/whatever target

You can deploy Rutta as a Helm chart https://github.com/helm/charts/pull/11499 and https://github.com/logary/logary/blob/master/src/services/rutta-helm-chart/README.md - it's very easy to gete started using it.

The above is probably the easiest as ZMQ together with the buffers of Logary will isolate your app from Rutta going down (also, these messages are stateless, so you can default to a Rutta replica set).

Since Rutta supports language-agnostic ingestion methods (listeners), you can log from all of your µ-services into the Rutta instance.
