### ISSUE TITLE
Make all Reservoirs Transducers

### ISSUE THREAD

**Issue by haf** [logary/logary#84]
Making all reservoirs transducers would allow Logary to have at least three tracks that a Message can go down:

 - Plain, as is. Through enrichers. To a target.
 - Plain, as it. Through a reservoir. The Reservoir transforms the Message to 1..n other messages. To a target.
 - Plain, as it, from HealthCheck. To a target.

Make it so that all Reservoirs in the code-base can be plugged into the configuration and properly configured to have their data sent to a target.

Definition of Done: we can configure a reservoir in the config, a Heka target and use these to view (in Grafana) the 90% and 10% percentile latencies of function calls in an example project.

I'm going to give three different gut-feeling explanations for what a transducer is

### A transducer is...

...two reducers. One reducer that's called at the end ('st -> 'a -> C<'st>), and a chain of reducers where each reducer calls the next until the value in the pipeline has been fully transformed and then the end reducer is called. The C is the context, e.g. a Hopac Job in our case.

### A transducer is...

...streaming reducers, where each reducer handles its own item. It also knows if it's completed or not (short-circuited) and it may or may not require a state (`mapping` doesn't, `takeN` does).

### A transducer is...

...a set of reducers that are structure preserving. A **final reducing function** that is structure collapsing, that you could call a *sink* for all the values produced to go into. A **constructor function** that takes the *set of reducers*, takes the *structure collapsing function* and creates a **transducer function**. Finally it is a **`transduce`** function that takes the *transducer function* and knows how to use it together with the streaming/list/callback-based/observable/enumerable/iterable data structure in question.

## Now...

You can now read [the code](https://github.com/logary/logary/blob/feature/object-model/src/Logary/Playground.fsx#L15) that implements the above.

## Aaand how does this relate to reservoirs?

The reservoirs have some state, which is made explicit in the above implementation. They may do IO, which is explicit through the use of Hopac's Job as the context. They take [*Message*s and update their internal state](https://github.com/logary/logary/blob/feature/object-model/src/Logary/Metric.fs#L230); e.g. by filling a location in an array. The don't do outbound IO, so they're stable (total functions) – hence not part of an actor, but can be part of the core library without error handling.

### Why do IO?

I'm thinking it might be possible to wrap a post-filter onto each of the reservoir's (reducer's) state output; saving it to do every nth interval and loading it on load, thereby making the system crash only without producing skewed or erroneous values while the buffers are filling up.

**Comment by cloudRoutine** [comment]
I did some experimenting with transducer a while back, but gave it up when I found I was getting slightly worse performance out of them than the `Seq` module and after I saw how [Nessos Streams](http://nessos.github.io/Streams/) annihilated them. 
> The main difference between LINQ/Seq and Streams is that LINQ is about composing external iterators (Enumerable/Enumerator) and Streams is based on the continuation-passing-style composition of internal iterators.

In principle this is the same thing that a transducer is doing (the lazy evaluation of sequences make them pretty similar to how transducers work too), sure you have to turn your collection into a stream but you can make them from any `IEnumerable` and in the end you'd be doing this with a transducer anyway. 

The short circuiting seems like a distinct benefit of the transducer, but using all of those object constructors in order to build and chain the transducers can get pretty expensive. It might be worthwhile to look at [the implementation of Streams](https://github.com/nessos/Streams/blob/master/src/Streams.Core/Streams.fs) and see if you can adapt it to a more "transducery" form.

[You can also check out a bunch of transducers I made and take anything you find useful.](https://gist.github.com/cloudRoutine/9c62477b91547d9d3523)

**Comment by haf** [comment]
I'm probably going to go for something that directly calls the next reducer rather than creating a tuple educer-reducer like transducers do. Thanks to @cloudRoutine for your input, I've studied your reply in depth, but like you say, there's probably dubious gains to be had right now.

**Comment by cloudRoutine** [comment]
the best thing to look at is probably @manofstick 's [Seq Composer PR](https://github.com/Microsoft/visualfsharp/pull/1570)
[Comment where he explains how the composers work](https://github.com/Microsoft/visualfsharp/pull/1570)

It's a much more clever (and more complicated) approach than what I was trying and avoids a lot of the runtime object construction dead weights that I've seen in most attempts at iterator fusion in F#.   [It's led to solid perf gains](https://github.com/Microsoft/visualfsharp/pull/1570#issuecomment-252385208), so it could be worth pursuing for Logary.
